from decimal import Decimal

THREAD_LAUNCHER_SLEEPING_TIME = 0.5
SOLVING_TIMEOUT = 5
USED_CORES_NUMBER = Decimal(4)
MAX_DELTA = Decimal(3)
DEFAULT_PARAMETERS_VALUES = {
    'minisat_core':            (True,
                                (Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.995'), Decimal('0.001')),
                                (Decimal('2'), Decimal('0.01')),
                                (Decimal('0.2'), Decimal('0.01')),
                                (Decimal('100'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2'), Decimal('1'))),
    'minisat_simp':            (True,
                                (Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.995'), Decimal('0.001')),
                                (Decimal('2'), Decimal('0.01')),
                                (Decimal('0.2'), Decimal('0.01')),
                                (Decimal('100'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2'), Decimal('1'))),
    'minisat_ClauseSplit':     (True,
                                (Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.995'), Decimal('0.001')),
                                (Decimal('2'), Decimal('0.01')),
                                (Decimal('0.2'), Decimal('0.01')),
                                (Decimal('100'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2147483647'), Decimal('10000')),
                                (Decimal('0'), Decimal('1000')),
                                (Decimal('2147483647'), Decimal('10000')),
                                (Decimal('0'), Decimal('1'))),
    'mipisat':                 (True,
                                (Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.999'), Decimal('0.001')),
                                (Decimal('2'), Decimal('0.01')),
                                (Decimal('0.2'), Decimal('0.01')),
                                (Decimal('100'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2'), Decimal('1'))),
    'pmcsat':                  (True,
                                (Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.995'), Decimal('0.001')),
                                (Decimal('2'), Decimal('0.01')),
                                (Decimal('0.2'), Decimal('0.01')),
                                (Decimal('100'), Decimal('1')),
                                (Decimal('2'), Decimal('1')),
                                (Decimal('2'), Decimal('1'))),
    'glucored+march_release':  ((Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.999'), Decimal('0.001')),
                                (Decimal('6'), Decimal('1')),
                                (Decimal('30'), Decimal('1'))),
    'glucan_static':           ((Decimal('0.95'), Decimal('0.001')),
                                (Decimal('0.999'), Decimal('0.001'))),
}